theme: minima
title: IPTF
description: Institutional Privacy Task Force

# Blog settings
permalink: /:title/
show_excerpts: true

# Social/SEO
url: "https://iptf.ethereum.org"
twitter:
  card: summary_large_image

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
